Vagrant.configure("2") do |config|
    # Utiliser l'image Ubuntu 20.04 LTS
    config.vm.box = "ubuntu/bionic64"
  
    # Configurer la VM
    # Configurer la VM pour utiliser libvirt (QEMU/KVM)
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    # Synchroniser le dossier courant avec /vagrant/docker-ssh dans la VM
    config.vm.synced_folder ".", "/vagrant/docker-ssh"
  
    # Provisionner la VM avec un script shell pour installer Docker et construire le conteneur
    config.vm.provision "shell", inline: <<-SHELL
      # Mettre à jour les paquets et installer les dépendances nécessaires
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  
      # Ajouter la clé GPG officielle de Docker
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  
      # Ajouter le dépôt Docker
      sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  
      # Mettre à jour les paquets et installer Docker
      sudo apt-get update
      sudo apt-get install -y docker-ce
  
      # Ajouter l'utilisateur vagrant au groupe docker
      sudo usermod -aG docker vagrant
  
      # Démarrer le service Docker
      sudo systemctl start docker
      sudo systemctl enable docker
  
      # Construire l'image Docker pour le serveur SSH
      cd /vagrant/docker-ssh
      sudo docker build --no-cache -t ssh-server .

      echo "SYNT{Rfpnynqr_qr_cevivyrtr_ivn_pncnovyvgvrf}" | tr  'N-ZA-Mn-za-m' 'A-Za-z' > /.password

      # Lancer le conteneur Docker avec le port SSH exposé
      sudo docker run -d -p 2222:22 --cap-add=ALL --privileged --security-opt apparmor=unconfined --device=/dev/sda1:/dev/sda1 --name ssh-container ssh-server
    SHELL
  
    # Configurer le port forwarding pour SSH du conteneur Docker
    config.vm.network "forwarded_port", guest: 2222, host: 2222
  
    # Configurer le port forwarding pour SSH de la VM Vagrant
    config.vm.network "forwarded_port", guest: 22, host: 2223
  
    # Configuration SSH pour Vagrant
    config.ssh.insert_key = false
  end
  